version: '3.8'

services:
  frontend:
    build:
      context: ./frontEnd/my-next-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./API/config:/app/config 