# 设置 邮件服务

email:
  email_address: "your_email@example.com"    # 邮箱地址
  username: "your_email@example.com"         # 邮箱用户名（通常和邮箱地址相同）
  smtp_server: "smtp.example.com"            # SMTP 服务器地址
  smtp_port: 587                             # SMTP 端口（587为TLS，465为SSL）
  auth_code: "your_authorization_code"       # 授权码（通常是应用专用密码）
  encryption: "TLS"                          # 加密方式（"SSL" 或 "TLS"）
  sender_name: "Your Name"                   # 发件人昵称（可选）
  recipient_email: "recipient@example.com"   # 收件人邮箱地址（可选）
  subject: "Default Subject"                 # 邮件默认主题（可选）

# 设置server酱
server_jiang:
  server_jiang_key: "SendKey"
  server_jiang_desp: "SendDesp"

