# 设置 邮件服务

# 设置api
api:
  api_port: 8080
  api_host: "0.0.0.0"
  api_path: "/api"
  api_body: "json"
  api_key: "1234567890"


email:
  email_address: "reschen@126.com"    # 邮箱地址
  username: "reschen@126.com"         # 邮箱用户名（通常和邮箱地址相同）
  smtp_server: "smtp.126.com"            # SMTP 服务器地址
  smtp_port: 587                             # SMTP 端口（587为TLS，465为SSL）
  auth_code: "WWsQwZ7XZ24QrMjD"       # 授权码（通常是应用专用密码）
  encryption: "TLS"                          # 加密方式（"SSL" 或 "TLS"）
  sender_name: "reschen's Send_Message_Server"                   # 发件人昵称（可选）

# 设置server酱
# https://sct.ftqq.com/sendkey
server_jiang:
  server_jiang_key: "SCT272922TVa1s7zaBifc0Ew0wbO396yq0"
  server_jiang_desp: "reschen's Send_Message_Server"

# 设置飞书
# https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/server-side-sdk/golang-sdk-guide/preparations
feishu:
  feishu_app_id: "cli_a7591da32d7f900c"
  feishu_app_secret: "KYQFHq11d1yD3OvwzV9SmfXbAMpGzjaH"
  feishu_user_id: "ou_128413e2dc6b98f81d1bc768ba757e7b"

# 设置钉钉
# https://www.oryoy.com/news/golang-shi-xian-ding-ding-ji-qi-ren-zi-dong-fa-song-xiao-xi-de-wan-zheng-zhi-nan.html
#  目前只支持 webhook
# https://oapi.dingtalk.com/robot/send?access_token=？YOUR_ACCESS_TOKEN
dingding:
  access_token: "785f7b96d6039f35ff57512be402eb6627792cfc401ccd042f3b6376ab7230a2"

# 设置微信https://wxpusher.zjiecode.com/docs/#/?id=spt
wx_push:
  wx_push_key: "AT_IcBsiMjmLvuURH1YOtpMbHRvAcMZ3he8"
  default_uid: "UID_DgSOBreg2VgXKN3gQk8pdCQObTN2" # 默认UID 可以为空 后期使用adduserlist添加用户

# 设置napcat
napcat:
  napcat_url: "http://reschen.cn:3000"
  napcat_token: "520521"
  napcat_qq: "1413024330"

